# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ju

before:
  hooks:
    - make setup
    - make lint
    - make test

builds:
  - binary: ju
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
    ldflags: -s -w

sign:
  artifacts: checksum

archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    386: i386
    amd64: x86_64

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'README.md'
